/*
 * SOCOMAP
 *
 * This API is for the new Socomap Protocol
 *
 * OpenAPI spec version: 0.0.1
 * Contact: development@infotech.de
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// Target Inbox for the Transmission
    /// </summary>
    [DataContract]
    public partial class TransmissionsCreateRequest : IEquatable<TransmissionsCreateRequest>
    { 
        /// <summary>
        /// Gets or Sets Party
        /// </summary>
        [Required]
        [DataMember(Name="party")]
        public string Party { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TransmissionsCreateRequest {\n");
            sb.Append("  Party: ").Append(Party).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((TransmissionsCreateRequest)obj);
        }

        /// <summary>
        /// Returns true if TransmissionsCreateRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of TransmissionsCreateRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TransmissionsCreateRequest other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Party == other.Party ||
                    Party != null &&
                    Party.Equals(other.Party)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Party != null)
                    hashCode = hashCode * 59 + Party.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(TransmissionsCreateRequest left, TransmissionsCreateRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(TransmissionsCreateRequest left, TransmissionsCreateRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
