/*
 * SOCOMAP
 *
 * This API is for the new Socomap Protocol
 *
 * OpenAPI spec version: 0.0.1
 * Contact: development@infotech.de
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// State of the Transaction
    /// </summary>
    [DataContract]
    public partial class TransmissionsStateResponse200 : IEquatable<TransmissionsStateResponse200>
    { 
        /// <summary>
        /// Is generated at the creation.
        /// </summary>
        /// <value>Is generated at the creation.</value>
        [DataMember(Name="created")]
        public DateTime? Created { get; set; }

        /// <summary>
        /// date of the data transfer for the transmission
        /// </summary>
        /// <value>date of the data transfer for the transmission</value>
        [DataMember(Name="transferred")]
        public DateTime? Transferred { get; set; }

        /// <summary>
        /// Gets or Sets Delivered
        /// </summary>
        [DataMember(Name="delivered")]
        public DateTime? Delivered { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TransmissionsStateResponse200 {\n");
            sb.Append("  Created: ").Append(Created).Append("\n");
            sb.Append("  Transferred: ").Append(Transferred).Append("\n");
            sb.Append("  Delivered: ").Append(Delivered).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((TransmissionsStateResponse200)obj);
        }

        /// <summary>
        /// Returns true if TransmissionsStateResponse200 instances are equal
        /// </summary>
        /// <param name="other">Instance of TransmissionsStateResponse200 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TransmissionsStateResponse200 other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Created == other.Created ||
                    Created != null &&
                    Created.Equals(other.Created)
                ) && 
                (
                    Transferred == other.Transferred ||
                    Transferred != null &&
                    Transferred.Equals(other.Transferred)
                ) && 
                (
                    Delivered == other.Delivered ||
                    Delivered != null &&
                    Delivered.Equals(other.Delivered)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Created != null)
                    hashCode = hashCode * 59 + Created.GetHashCode();
                    if (Transferred != null)
                    hashCode = hashCode * 59 + Transferred.GetHashCode();
                    if (Delivered != null)
                    hashCode = hashCode * 59 + Delivered.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(TransmissionsStateResponse200 left, TransmissionsStateResponse200 right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(TransmissionsStateResponse200 left, TransmissionsStateResponse200 right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
