/*
 * SOCOMAP
 *
 * This API is for the new Socomap Protocol
 *
 * OpenAPI spec version: 0.0.1
 * Contact: development@infotech.de
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// returns the id of the new transmission
    /// </summary>
    [DataContract]
    public partial class TransmissionsCreateResponse200 : IEquatable<TransmissionsCreateResponse200>
    { 
        /// <summary>
        /// the ident of the new Transmission
        /// </summary>
        /// <value>the ident of the new Transmission</value>
        [Required]
        [DataMember(Name="tid")]
        public string Tid { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TransmissionsCreateResponse200 {\n");
            sb.Append("  Tid: ").Append(Tid).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((TransmissionsCreateResponse200)obj);
        }

        /// <summary>
        /// Returns true if TransmissionsCreateResponse200 instances are equal
        /// </summary>
        /// <param name="other">Instance of TransmissionsCreateResponse200 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TransmissionsCreateResponse200 other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Tid == other.Tid ||
                    Tid != null &&
                    Tid.Equals(other.Tid)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Tid != null)
                    hashCode = hashCode * 59 + Tid.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(TransmissionsCreateResponse200 left, TransmissionsCreateResponse200 right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(TransmissionsCreateResponse200 left, TransmissionsCreateResponse200 right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
