// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SocomapLib;
using System;

namespace Socomap.Migrations
{
    [DbContext(typeof(TransmissionContext))]
    partial class TransmissionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SocomapLib.Inbox", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApiKey");

                    b.Property<string>("Email");

                    b.HasKey("Id");

                    b.ToTable("Inboxes");
                });

            modelBuilder.Entity("SocomapLib.Transmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("BinaryContent");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime?>("DeliveredOn");

                    b.Property<string>("TargetInboxId");

                    b.Property<DateTime?>("TransferredOn");

                    b.HasKey("Id");

                    b.HasIndex("TargetInboxId");

                    b.ToTable("Transmissions");
                });

            modelBuilder.Entity("SocomapLib.Transmission", b =>
                {
                    b.HasOne("SocomapLib.Inbox", "TargetInbox")
                        .WithMany()
                        .HasForeignKey("TargetInboxId");
                });
#pragma warning restore 612, 618
        }
    }
}
